### ISSUE TITLE
This is amazing!

### ISSUE THREAD

**Issue by nobody5050** [Podrum/RakNet.py#1]
Hey this project is amazing, I thought I was the only one still interested in pyraklib. Would you mind if I fork this project for mcbes? https://github.com/mcbes

Also if you are interested I would love to have you help build mcbes

**Comment by MFDGaming** [comment]
This is still under development and this is aimed to manly be for a server software that I am making called Podrum

**Comment by MFDGaming** [comment]
And also this project is open-source

**Comment by MFDGaming** [comment]
@nobody5050 by the way it is not based of pyraklib (that thing you read was a small misunderstanding of nougator

**Comment by MFDGaming** [comment]
It is based off the pocketmine raklib 0.12.0

**Comment by RaVenInTheDark** [comment]
How would I potentially use this in my own code? PyRakLib was all I was able to find until now, and that has no documentation + devs that refuse to provide usage help

**Comment by MFDGaming** [comment]
this is unfinished and when it is dont it will be supported

**Comment by MFDGaming** [comment]
also i am making this by my self (no other devs)

**Comment by MFDGaming** [comment]
@RaVenInTheDark sorry for answering so many day later but a thing i can say is that it is not useable yet

**Comment by nougator** [comment]
Thx
